### ISSUE TITLE
Compile errors in jooq-example

### ISSUE THREAD

**Issue by braendi** [PacktPublishing/Data-Centric-Applications-with-Vaadin-8#1]
Hi
I'm working on the first chapter of your book. After importing the project into my Eclipse workspace and installing lombok, a single project still shows compilation errors: jooq-example. Mainly because the import of `packt.vaadin.chapter06.jooq.public_.tables.records.MessagesRecord` and `packt.vaadin.chapter06.jooq.public_.Tables.MESSAGES` fails. I could not find those classes anywhere in the project structure.
Regards
Stefan

**Comment by alejandro-du** [comment]
Hi, please check the “Understanding the source code” section of chapter 1 (page 7) and follow the instructions to compile the projects.
